### ISSUE TITLE
List of valid variables to carry over to links.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Arkia-Links-Site#1]
@talovdat to my understanding we are suppose to transfer all the variables we get when showing this page to the destination page when user clicks on link to preserve sessions and stuff. I need a list of valid variable names to carry over in order to avoid specific attacks.

**Comment by talovdat** [comment]
List of valid variable names in Mladen's mail.

**Comment by MeanEYE** [comment]
@eyalway2cu did this.
